### ISSUE TITLE
正規表現を用いた指示の振り分け部分の作成

### ISSUE THREAD

**Issue by kbc14a13** [kbc14a13/sphero_voice#13]
現状必要な認識は前進、左、右、後退、停止の５つです。

**Comment by Huruikagi** [comment]
- 関数 `extructCommand` を定義する
  -  引数 `message` (文字列 "前に", "前進"、”止まれ”)など
  -  返り値 "forword", "badk"など commandの値としてとりうるもの
- 内部処理
  - それぞれのコマンドに対応する正規表現を定義する
  - messageを正規表現を使って順番にテストし、いずれかに一致した時点で、コマンド文字列をリターンする

**Comment by kbc14a01** [comment]
マイクに喋った言葉を認識して、言葉によって動作を区別することはできるようになった。
正規表現も適応している。
